# Homework 3: PCA/Hyperparameter/CV
Data source: http://archive.ics.uci.edu/ml/datasets/Polish+companies+bankruptcy+data

In [31]:
from scipy.io import arff
import pandas as pd
import numpy as np

In [32]:
data = arff.loadarff('4year.arff')
df = pd.DataFrame(data[0])
df

Attr1    Attr2     Attr3    Attr4     Attr5     Attr6     Attr7  \
0     0.159290  0.46240  0.077730  1.16830  -44.8530  0.467020  0.189480   
1    -0.127430  0.46243  0.269170  1.75170    7.5970  0.000925 -0.127430   
2     0.070488  0.23570  0.527810  3.23930  125.6800  0.163670  0.086895   
3     0.136760  0.40538  0.315430  1.87050   19.1150  0.504970  0.136760   
4    -0.110080  0.69793  0.188780  1.27130  -15.3440  0.000000 -0.110080   
...        ...      ...       ...      ...       ...       ...       ...   
9787  0.004676  0.54949  0.192810  1.38990  -39.0640  0.004676  0.013002   
9788 -0.027610  0.60748 -0.029762  0.90591  -20.9230 -0.027610 -0.027610   
9789 -0.238290  0.62708  0.090374  1.61250   -1.0692 -0.238290 -0.240360   
9790  0.097188  0.75300 -0.327680  0.43850 -214.2400 -0.331300  0.104280   
9791  0.021416  0.48678  0.148940  1.30670  -24.2820  0.021416  0.027253   

        Attr8    Attr9   Attr10  ...    Attr56    Attr57   Attr58    Attr59  \
0     0.82895  1.12230  0.38330  ...  0.108990  0.415570  0.89101  0.001422   
1     1.16250  1.29440  0.53757  ... -0.089372 -0.237040  1.06250  0.150410   
2     2.87180  1.05740  0.67689  ...  0.054286  0.104130  0.94571  0.000000   
3     1.45390  1.11440  0.58938  ...  0.102630  0.232030  0.89737  0.073024   
4     0.43282  1.73500  0.30207  ...  0.439880 -0.364400  0.57153  0.000000   
...       ...      ...      ...  ...       ...       ...      ...       ...   
9787  0.78627  0.97093  0.43205  ... -0.029937  0.010823  1.02990  0.127190   
9788  0.55161  1.00730  0.33509  ...  0.007198 -0.082395  0.99280  0.868910   
9789  0.28322  0.80307  0.17760  ... -0.245220 -1.341700  1.24520  2.700100   
9790  0.32803  0.98145  0.24700  ...  0.288240  0.393470  0.68127  0.508850   
9791  1.05320  1.00140  0.51267  ...  0.001393  0.041773  0.99861  0.002146   

       Attr60   Attr61   Attr62  Attr63    Attr64  class  
0      7.7928   4.9914  119.810  3.0465   3.05600   b'0'  
1      5.4327   3.4629  100.970  3.6150   3.47250   b'0'  
2      7.1070   3.3808   76.076  4.7978   4.78180   b'0'  
3      6.1384   4.2241   88.299  4.1337   4.64840   b'0'  
4     18.8010   2.7925  146.390  2.4934  15.03600   b'0'  
...       ...      ...      ...     ...       ...    ...  
9787   3.8159   3.3892  146.860  2.4854   3.93150   b'1'  
9788  23.0280  27.1360   37.047  9.8523   4.36810   b'1'  
9789   6.5694   4.1781   88.883  4.1065   0.79501   b'1'  
9790   4.3246  35.5030  217.030  1.6818   1.31910   b'1'  
9791   6.7582   4.9171   98.421  3.7085   4.92950   b'1'  

[9792 rows x 65 columns]

In [33]:
df['bankruptcy'] = (df['class']==b'1')
del df['class']
df.columns = ['X{0:02d}'.format(k) for k in range(1,65)] + ['bankruptcy']

In [34]:
df.describe()


X01          X02          X03           X04           X05  \
count  9791.000000  9791.000000  9791.000000   9749.000000  9.771000e+03   
mean      0.043019     0.596404     0.130959      8.136600  6.465164e+01   
std       0.359321     4.587122     4.559074    290.647281  1.475939e+04   
min     -12.458000     0.000000  -445.910000     -0.045319 -3.794600e+05   
25%       0.001321     0.263145     0.020377      1.047000 -5.121700e+01   
50%       0.041364     0.467740     0.199290      1.591800 -5.557600e-02   
75%       0.111130     0.689255     0.410670      2.880400  5.573200e+01   
max      20.482000   446.910000    22.769000  27146.000000  1.034100e+06   

               X06          X07           X08          X09          X10  ...  \
count  9791.000000  9791.000000   9773.000000  9792.000000  9791.000000  ...   
mean     -0.059273     0.059446     19.884016     1.882296     0.389040  ...   
std       6.812754     0.533344    698.697015    17.674650     4.590299  ...   
min    -486.820000   -12.458000     -1.848200    -0.032371  -445.910000  ...   
25%      -0.000578     0.003004      0.428300     1.006675     0.294440  ...   
50%       0.000000     0.048820      1.088700     1.161300     0.510450  ...   
75%       0.065322     0.126940      2.691000     1.970225     0.714290  ...   
max     322.200000    38.618000  53209.000000  1704.800000    12.602000  ...   

                X55          X56          X57          X58          X59  \
count  9.792000e+03  9771.000000  9791.000000  9776.000000  9791.000000   
mean   7.686330e+03    -0.992263     0.035022     1.133287     0.856053   
std    7.605261e+04    77.007971     8.945365     8.038201    26.393305   
min   -7.132200e+05 -7522.100000  -597.420000   -30.892000  -284.380000   
25%    2.184000e+01     0.003121     0.008768     0.885722     0.000000   
50%    9.503300e+02     0.043679     0.098026     0.958305     0.002129   
75%    4.694550e+03     0.117170     0.242680     0.996163     0.211790   
max    6.123700e+06   112.020000   226.760000   668.750000  1661.000000   

                 X60            X61           X62          X63           X64  
count    9178.000000    9760.000000  9.771000e+03  9749.000000   9561.000000  
mean      118.156064      25.194430  2.015157e+03     8.660813     35.949619  
std      3230.316692    1099.260821  1.171461e+05    60.838202    483.318623  
min         0.000000     -12.656000 -1.496500e+04    -0.024390     -0.000015  
25%         5.356325       4.267700  4.323400e+01     2.938800      2.012900  
50%         9.482000       6.283550  7.472900e+01     4.848900      4.041600  
75%        19.506000       9.938200  1.233450e+02     8.363800      9.413500  
max    251570.000000  108000.000000  1.077900e+07  5662.400000  21153.000000  

[8 rows x 64 columns]

In [35]:
sum(df.bankruptcy == True)

515

In [36]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
X_imp = imp_mean.fit_transform(df.values)

In [37]:
from sklearn.model_selection import train_test_split

X, y = X_imp[:, :-1], X_imp[:, -1]

X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

In [38]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## Find the 3 most important features


In [39]:
import numpy as np
cov_mat = np.cov(X_train_std.T)
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)

print('\nEigenvalues \n%s' % eigen_vals)


Eigenvalues 
[ 1.11994034e+01  5.83874380e+00  5.19411944e+00  4.23087992e+00
  3.42390435e+00  3.05582599e+00  2.89650494e+00  2.40639848e+00
  1.98345880e+00  1.75112935e+00  1.58603094e+00  1.52146524e+00
  1.37025443e+00  1.24122096e+00  1.19873371e+00  1.13367446e+00
  1.05959066e+00  8.77951425e-01  9.38667351e-01  9.63611349e-01
  1.00527344e+00  9.98164015e-01  1.00276500e+00  9.99996249e-01
  7.99193954e-01  7.62586585e-01  6.67570737e-01  6.42238369e-01
  5.21518660e-01  4.71038329e-01  4.19057280e-01  3.84346082e-01
  3.30072008e-01  2.01397457e-01  1.82480024e-01  1.51766497e-01
  1.21514504e-01  1.06714888e-01  6.79438980e-02  6.07197160e-02
  5.34654673e-02  3.68997728e-02  2.76603363e-02  2.59667279e-02
  2.62746675e-02  2.24571976e-02  1.95169451e-02  1.03031382e-02
  6.78081564e-03  4.86195308e-03  2.68403923e-03  1.88066779e-03
  1.37471213e-03  4.76676660e-04  3.16976043e-04  3.03001450e-04
  1.14591427e-04  4.59843804e-05  2.79795386e-05  5.76146045e-07
  4.5840973

In [40]:
tot = sum(eigen_vals)
var_exp = [(i / tot) for i in sorted(eigen_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

In [41]:
# Make a list of (eigenvalue, eigenvector) tuples
eigen_pairs = [(np.abs(eigen_vals[i]), eigen_vecs[:, i])
               for i in range(len(eigen_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eigen_pairs.sort(key=lambda k: k[0], reverse=True)

In [42]:
w = np.hstack((eigen_pairs[0][1][:, np.newaxis],
               eigen_pairs[1][1][:, np.newaxis],eigen_pairs[2][1][:, np.newaxis]))
print('Matrix W:\n', w)

Matrix W:
 [[-1.05238569e-01 -2.07768541e-02  1.65458612e-01]
 [ 5.11820101e-02  2.43796426e-02 -3.97156466e-01]
 [-5.97899011e-02 -1.93289114e-02  3.43191145e-01]
 [-5.27517942e-03 -1.83592964e-03  1.68204702e-02]
 [-3.08371021e-03  1.94240189e-02  3.54661847e-02]
 [-2.17280068e-02 -5.91771392e-03  9.30400489e-02]
 [-2.86581578e-01  5.94078649e-04  5.94987619e-03]
 [-1.35505580e-02 -9.29763106e-04  7.35249042e-03]
 [-2.65924355e-01  1.42052028e-02 -1.05221371e-01]
 [-5.38807809e-02 -2.27245211e-02  4.00567323e-01]
 [-2.87136166e-01  2.24855242e-03 -1.68113933e-03]
 [-3.26018318e-02 -4.78163110e-03 -7.79089084e-03]
 [-4.00541039e-03 -3.47954351e-01 -2.52594904e-02]
 [-2.86581578e-01  5.94078672e-04  5.94987613e-03]
 [ 8.05521429e-04 -4.38969433e-04 -1.27798280e-03]
 [-3.46528669e-02 -2.44317736e-03 -1.37056401e-02]
 [-1.35511335e-02 -9.31288646e-04  7.36570111e-03]
 [-2.86581569e-01  5.94087307e-04  5.94985074e-03]
 [-4.75840982e-03 -3.77522535e-01 -2.45760462e-02]
 [ 4.63333520e-03  2

In [43]:
X_train_std[0].dot(w)

array([ 0.27866736, -0.12838885,  0.83934251])

In [44]:
from sklearn.decomposition import PCA

pca = PCA()
X_train_pca = pca.fit_transform(X_train_std)
pca.explained_variance_ratio_

array([1.74965147e-01, 9.12170614e-02, 8.11462753e-02, 6.60978536e-02,
       5.34907000e-02, 4.77403147e-02, 4.52512866e-02, 3.75944904e-02,
       3.09870220e-02, 2.73574041e-02, 2.47781178e-02, 2.37694259e-02,
       2.14071017e-02, 1.93912479e-02, 1.87274814e-02, 1.77110790e-02,
       1.65536886e-02, 1.57051058e-02, 1.56659171e-02, 1.56226617e-02,
       1.55940372e-02, 1.50542306e-02, 1.46645375e-02, 1.37159896e-02,
       1.24855836e-02, 1.19136769e-02, 1.04292709e-02, 1.00335104e-02,
       8.14754016e-03, 7.35890007e-03, 6.54681467e-03, 6.00453134e-03,
       5.15662266e-03, 3.14637614e-03, 2.85083437e-03, 2.37100553e-03,
       1.89838710e-03, 1.66717684e-03, 1.06146851e-03, 9.48607140e-04,
       8.35276042e-04, 5.76474830e-04, 4.32129697e-04, 4.10481782e-04,
       4.05670927e-04, 3.50842516e-04, 3.04907775e-04, 1.60963047e-04,
       1.05934786e-04, 7.59569331e-05, 4.19319942e-05, 2.93811469e-05,
       2.14767430e-05, 7.44698613e-06, 4.95202807e-06, 4.73370690e-06,
      

In [50]:
pca = PCA(n_components=3)#use only first 3 variable
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_test_pca[:]

array([[-1.05481854,  0.39843857,  7.08442613],
       [ 0.69457967, -0.1145366 , -0.87772003],
       [-0.00777243, -0.08299795, -0.3758454 ],
       ...,
       [-0.12761749, -0.05178877, -0.16753027],
       [-0.2596154 , -0.05444861, -0.29617052],
       [-0.42872625, -0.05019801, -0.203546  ]])

## Apply LR/SVM/Decision Tree Below

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# and put more...

In [55]:
lr = LogisticRegression(penalty='l1',C=0.01,random_state=1,solver='liblinear')# complete
lr.fit(X_train_std,y_train)
print('Training accuracy:', lr.score(X_train_std, y_train))
print('Test accuracy:', lr.score(X_test_std, y_test))

Training accuracy: 0.9474759264662971
Test accuracy: 0.9469026548672567


In [56]:
lr.intercept_

array([-2.63361973])

In [57]:
lr.coef_[lr.coef_!=0].shape # check the number of the features with non-zero weights

(2,)

In [58]:
# redefine X_train_std and X_test_std
X_train_std = X_train_std[:, lr.coef_[0]!=0]
X_test_std = X_test_std[:, lr.coef_[0]!=0]

In [59]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

pipe_lr = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        LogisticRegression(random_state=1,solver='liblinear'))

pipe_lr.fit(X_train, y_train)
y_pred = pipe_lr.predict(X_test)
print('Test Accuracy:',pipe_lr.score(X_train, y_train))
print('Test accuracy:',pipe_lr.score(X_test, y_test))

Test Accuracy: 0.946892325649256
Test accuracy: 0.9462219196732471


In [60]:
pipe_lr = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        SVC(kernel = 'rbf',random_state=1,gamma=2,C=1))

pipe_lr.fit(X_train, y_train)
y_pred = pipe_lr.predict(X_test)
print('Test Accuracy:',pipe_lr.score(X_train, y_train))
print('Test Accuracy:',pipe_lr.score(X_test, y_test))

Test Accuracy: 0.9489349285088999
Test Accuracy: 0.9472430224642614


In [62]:
pipe_lr = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        DecisionTreeClassifier(criterion = 'gini', max_depth=4, random_state = 1))

pipe_lr.fit(X_train, y_train)
y_pred = pipe_lr.predict(X_test)
y_pred = pipe_lr.predict(X_test)
print('Test Accuracy:',pipe_lr.score(X_train, y_train))
print('Test Accuracy:',pipe_lr.score(X_test, y_test))

Test Accuracy: 0.948497227896119
Test Accuracy: 0.9472430224642614


In [63]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

penalty_range = ['l2','l1','elasticnet']

param_range = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
solver_range = ['liblinear','sag','newton-cg']
param_grid = [{'penalty': ['l2'], 
               'C':param_range,'solver':solver_range},
             {'penalty': ['l1'], 
               'C':param_range,'solver':['liblinear']}]

gs = GridSearchCV(estimator= LogisticRegression(random_state=1), 
                  param_grid=param_grid, 
                  scoring='accuracy',
                  refit=True,
                  cv=10,
                  n_jobs=-1)
gs = gs.fit(X_train_pca, y_train)
print(gs.best_score_)
print(gs.best_params_)

0.9474759264662971
{'C': 0.0001, 'penalty': 'l2', 'solver': 'sag'}


/Users/maihemutialimujiang/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
